export type ImageCategory = "man" | "hands" | "garment" | "house" | "archive";

export type ImageEntry = {
  id: string;
  desktopSrc: string;
  mobileSrc: string;
  alt: string;
  category: ImageCategory;
  desktopObjectPosition: string;
  tabletObjectPosition?: string;
  mobileObjectPosition: string;
  desktopAspect?: string;
  mobileAspect?: string;
  quality?: number;
  notes?: string;
  /** Internal only. Never shown on the site. */
  temporary?: boolean;
  sourceType?: "photograph" | "ai-concept";
  replacementRequired?: boolean;
};

export const images = {
  heroCampaign: {
    id: "heroCampaign",
    desktopSrc: "/images/campaign/ceo-rules-hero-approved.jpg",
    mobileSrc: "/images/campaign/ceo-rules-hero-approved.jpg",
    alt: "A tailor fitting a midnight wool jacket, basting stitches visible",
    category: "garment",
    desktopObjectPosition: "center 42%",
    tabletObjectPosition: "58% 38%",
    mobileObjectPosition: "70% 30%",
    desktopAspect: "3/2",
    mobileAspect: "3/2",
    quality: 84,
    notes:
      "Approved fitting campaign. Native 1024×682 — do not request wider. Cloth-book spines are baked and not mill proof. Dedicated mobile plate when supplied.",
    temporary: true,
    sourceType: "ai-concept",
    replacementRequired: true,
  },
  clothSelection: {
    id: "clothSelection",
    desktopSrc: "/images/campaign/cloth-selection.jpg",
    mobileSrc: "/images/campaign/cloth-selection.jpg",
    alt: "Hands choosing cloth from open sample books",
    category: "hands",
    desktopObjectPosition: "center 42%",
    tabletObjectPosition: "center 40%",
    mobileObjectPosition: "center 38%",
    desktopAspect: "3/2",
    mobileAspect: "3/2",
    quality: 82,
    notes: "Approved cloth selection. Native 1024×682. Cap ~512 CSS. Human choice, not a mill ad.",
  },
  clothLoroBook: {
    id: "clothLoroBook",
    desktopSrc: "/images/campaign/cloth-loro-book.jpg",
    mobileSrc: "/images/campaign/cloth-loro-book.jpg",
    alt: "An open cloth book, swatches fanned under a tailor's hand",
    category: "garment",
    desktopObjectPosition: "88% 36%",
    tabletObjectPosition: "90% 38%",
    mobileObjectPosition: "92% 40%",
    desktopAspect: "4/5",
    mobileAspect: "4/5",
    quality: 80,
    notes:
      "Approved overhead book. Native 1024×1024. Square crop toward swatches and the right hand — not the mill title page. Cap ~320 CSS.",
  },
  clothTable: {
    id: "clothTable",
    desktopSrc: "/images/campaign/cloth-table.jpg",
    mobileSrc: "/images/campaign/cloth-table.jpg",
    alt: "A tailored man selecting cloth at a wooden table",
    category: "garment",
    desktopObjectPosition: "center 48%",
    tabletObjectPosition: "center 48%",
    mobileObjectPosition: "center 48%",
    desktopAspect: "3/2",
    mobileAspect: "3/2",
    quality: 80,
    notes:
      "Approved but unused on the homepage. Native 1024×1024 with letterbox bars — crop 3/2 from centre if placed. Fallback if clothSelection feels too clinical.",
  },
  craftCutShears: {
    id: "craftCutShears",
    desktopSrc: "/images/campaign/craft-cut-shears.png",
    mobileSrc: "/images/campaign/craft-cut-shears.png",
    alt: "Tailoring shears cutting a length of herringbone cloth",
    category: "hands",
    desktopObjectPosition: "center 42%",
    tabletObjectPosition: "center 44%",
    mobileObjectPosition: "center 40%",
    desktopAspect: "16/9",
    mobileAspect: "16/9",
    quality: 82,
    notes: "Approved cut. Native 1024×576. Keep 16/9. Cap ~512 CSS.",
  },
  craftFitBasted: {
    id: "craftFitBasted",
    desktopSrc: "/images/campaign/craft-fit-basted.png",
    mobileSrc: "/images/campaign/craft-fit-basted.png",
    alt: "A tailor fitting a brown basted jacket on the client",
    category: "man",
    desktopObjectPosition: "center 42%",
    tabletObjectPosition: "center 40%",
    mobileObjectPosition: "center 38%",
    desktopAspect: "3/2",
    mobileAspect: "3/2",
    quality: 80,
    replacementRequired: true,
    notes:
      "Approved basted fitting. Native 600×400 — do not exceed 360 CSS. Emphasize by placement, not scale.",
  },
  craftFinishThread: {
    id: "craftFinishThread",
    desktopSrc: "/images/campaign/craft-finish-thread.png",
    mobileSrc: "/images/campaign/craft-finish-thread.png",
    alt: "A tailor's hands holding a length of thread at the workbench",
    category: "hands",
    desktopObjectPosition: "center 38%",
    tabletObjectPosition: "center 36%",
    mobileObjectPosition: "center 34%",
    desktopAspect: "3/2",
    mobileAspect: "3/2",
    quality: 82,
    notes: "Approved finish / handwork. Native 1024×682. Cap ~512 CSS.",
  },
  storefrontDay: {
    id: "storefrontDay",
    desktopSrc: "/images/storefront.webp",
    mobileSrc: "/images/storefront.webp",
    alt: "The CEO Rules storefront in daylight, Bandra, with the wooden house sign above the entrance",
    category: "house",
    desktopObjectPosition: "center 42%",
    tabletObjectPosition: "36% 40%",
    mobileObjectPosition: "30% 38%",
    desktopAspect: "3/2",
    mobileAspect: "4/5",
    quality: 80,
    notes:
      "1360×1020. Honest max ~680 CSS at 2×. Contained 3/2 plate — never 21:9 full-bleed. Street clutter; crop toward the sign and door.",
  },
  storefrontNight: {
    id: "storefrontNight",
    desktopSrc: "/images/IMG_3732.jpg",
    mobileSrc: "/images/IMG_3732.jpg",
    alt: "The CEO Rules storefront at night, Bandra",
    category: "house",
    desktopObjectPosition: "center 40%",
    mobileObjectPosition: "center 38%",
    notes: "Night exposure. Too cinematic for the sunlit system.",
  },
  conversation: {
    id: "conversation",
    desktopSrc: "/images/atelier-conversation.webp",
    mobileSrc: "/images/atelier-conversation.webp",
    alt: "Anis Soomar in conversation with a client over coffee at the atelier",
    category: "man",
    desktopObjectPosition: "center 28%",
    tabletObjectPosition: "center 26%",
    mobileObjectPosition: "center 22%",
    desktopAspect: "4/5",
    mobileAspect: "4/5",
    quality: 78,
    notes:
      "1020×1020. Strongest authentic Anis plate. Cap near 512 CSS on desktop so 2× stays honest. Faces sit centre — do not force landscape.",
  },
  jacketOnForm: {
    id: "jacketOnForm",
    desktopSrc: "/images/IMG_3731.jpg",
    mobileSrc: "/images/IMG_3731.jpg",
    alt: "A jacket taking shape on the form, tape measure across the chest",
    category: "garment",
    desktopObjectPosition: "48% 8%",
    tabletObjectPosition: "50% 6%",
    mobileObjectPosition: "52% 4%",
    desktopAspect: "1/1",
    mobileAspect: "1/1",
    quality: 82,
    notes:
      "1080×1320. Watermark at the bottom. Square crop from the top hides the mark. Cap ~496 CSS.",
  },
  canvasChest: {
    id: "canvasChest",
    desktopSrc: "/images/IMG_3739.jpg",
    mobileSrc: "/images/IMG_3739.jpg",
    alt: "A hand-basted canvas chest taking shape on the form",
    category: "hands",
    desktopObjectPosition: "center 38%",
    tabletObjectPosition: "center 36%",
    mobileObjectPosition: "center 34%",
    desktopAspect: "3/2",
    mobileAspect: "3/2",
    quality: 78,
    notes: "1061×764. Intimate construction detail. Cap ~320 CSS. Prefer 3/2 over a tall crop.",
  },
  lapelSquare: {
    id: "lapelSquare",
    desktopSrc: "/images/IMG_3726.jpg",
    mobileSrc: "/images/IMG_3726.jpg",
    alt: "A jacket lapel with a folded pocket square",
    category: "garment",
    desktopObjectPosition: "58% 42%",
    tabletObjectPosition: "50% 40%",
    mobileObjectPosition: "48% 38%",
    desktopAspect: "3/4",
    mobileAspect: "3/4",
    quality: 80,
    notes: "Highest-resolution still (1206×2089). Precision detail only — keep around 320 CSS.",
  },
  clothEdges: {
    id: "clothEdges",
    desktopSrc: "/images/IMG_3736.jpg",
    mobileSrc: "/images/IMG_3736.jpg",
    alt: "A fan of jacketing cloths, edge on",
    category: "garment",
    desktopObjectPosition: "center 42%",
    tabletObjectPosition: "center 44%",
    mobileObjectPosition: "center 46%",
    desktopAspect: "3/2",
    mobileAspect: "3/2",
    quality: 80,
    notes: "1074×1084. Contained landscape ~540 CSS. Do not full-bleed 16/9.",
  },
  anisFitting: {
    id: "anisFitting",
    desktopSrc: "/images/IMG_3728.jpg",
    mobileSrc: "/images/IMG_3728.jpg",
    alt: "Anis Soomar fitting a jacket at the shoulder",
    category: "man",
    desktopObjectPosition: "center 22%",
    tabletObjectPosition: "center 20%",
    mobileObjectPosition: "42% 18%",
    desktopAspect: "1/1",
    mobileAspect: "4/5",
    quality: 80,
    notes: "1075×1089. Human fit moment. Cap ~540 CSS. Wide crops eat the heads.",
  },
  anisStitching: {
    id: "anisStitching",
    desktopSrc: "/images/founder-stitching.webp",
    mobileSrc: "/images/founder-stitching.webp",
    alt: "Anis Soomar at work, hand-stitching",
    category: "hands",
    desktopObjectPosition: "62% 18%",
    tabletObjectPosition: "58% 16%",
    mobileObjectPosition: "54% 14%",
    desktopAspect: "4/5",
    mobileAspect: "4/5",
    quality: 72,
    notes: "826px, heavily compressed. Do not use large on the homepage.",
  },
  suitWorn: {
    id: "suitWorn",
    desktopSrc: "/images/IMG_3730.jpg",
    mobileSrc: "/images/IMG_3730.jpg",
    alt: "A man in a bespoke checked suit, adjusting a cuff",
    category: "garment",
    desktopObjectPosition: "center 8%",
    tabletObjectPosition: "center 6%",
    mobileObjectPosition: "center 4%",
    desktopAspect: "3/2",
    mobileAspect: "5/4",
    quality: 80,
    notes:
      "1080×1085 with a bottom watermark. 3/2 from the top hides the mark. Cap ~540 CSS. Do not 4/5.",
  },
  tuxedoDetail: {
    id: "tuxedoDetail",
    desktopSrc: "/images/tuxedo-detail.webp",
    mobileSrc: "/images/tuxedo-detail.webp",
    alt: "A black tuxedo on the stand, satin lapel and pleated shirt",
    category: "garment",
    desktopObjectPosition: "center 28%",
    tabletObjectPosition: "center 26%",
    mobileObjectPosition: "center 24%",
    desktopAspect: "3/4",
    mobileAspect: "3/4",
    notes: "Only 574px wide. House still-life only — keep under ~280 CSS.",
  },
  silkTies: {
    id: "silkTies",
    desktopSrc: "/images/IMG_3738.jpg",
    mobileSrc: "/images/IMG_3738.jpg",
    alt: "Folded silk ties in the house's patterns",
    category: "garment",
    desktopObjectPosition: "center 40%",
    tabletObjectPosition: "center 38%",
    mobileObjectPosition: "center 36%",
    desktopAspect: "3/4",
    mobileAspect: "3/4",
    quality: 80,
    notes: "1206×1491. Rules by Anis vertical. Cap ~360 CSS.",
  },
  exclusiveCloth: {
    id: "exclusiveCloth",
    desktopSrc: "/images/IMG_3735.jpg",
    mobileSrc: "/images/IMG_3735.jpg",
    alt: "Navy cloth woven exclusively for CEO Rules by Huddersfield",
    category: "garment",
    desktopObjectPosition: "center",
    mobileObjectPosition: "center",
    notes: "Instagram poster border. Do not use as a primary homepage plate.",
  },
  atelierCloth: {
    id: "atelierCloth",
    desktopSrc: "/images/IMG_3727.jpg",
    mobileSrc: "/images/IMG_3727.jpg",
    alt: "Cloths laid out on the cutting table in the Bandra atelier",
    category: "house",
    desktopObjectPosition: "center top",
    tabletObjectPosition: "center top",
    mobileObjectPosition: "center top",
    desktopAspect: "1/1",
    mobileAspect: "1/1",
    quality: 80,
    notes:
      "1206×1177. Authentic atelier still for The House. Keep small — around 272 CSS. Crop from the bottom only so the top of the shelves stays in frame.",
  },
  houseHero: {
    id: "houseHero",
    desktopSrc: "/images/house-hero.jpg",
    mobileSrc: "/images/house-hero.jpg",
    alt: "Anis Soomar in the atelier, in conversation over coffee",
    category: "man",
    desktopObjectPosition: "center",
    tabletObjectPosition: "center",
    mobileObjectPosition: "center",
    desktopAspect: "4/3",
    mobileAspect: "4/3",
    quality: 82,
    notes:
      "1024×767. The House page hero. Near-native 4/3 frame; if any crop is required, take it equally from all sides (center).",
  },
  clothBook: {
    id: "clothBook",
    desktopSrc: "/images/IMG_3736.jpg",
    mobileSrc: "/images/IMG_3736.jpg",
    alt: "A cloth book, waiting for a professional photograph",
    category: "garment",
    desktopObjectPosition: "center",
    mobileObjectPosition: "center",
    replacementRequired: true,
    notes: "Shoot slot. Unused until a cloth-book photograph exists.",
  },
  clothHands: {
    id: "clothHands",
    desktopSrc: "/images/IMG_3736.jpg",
    mobileSrc: "/images/IMG_3736.jpg",
    alt: "Hands over cloth swatches, waiting for a professional photograph",
    category: "hands",
    desktopObjectPosition: "center",
    mobileObjectPosition: "center",
    replacementRequired: true,
    notes: "Shoot slot. Unused until a hands/swatch photograph exists.",
  },
  anisPortrait: {
    id: "anisPortrait",
    desktopSrc: "/images/atelier-conversation.webp",
    mobileSrc: "/images/atelier-conversation.webp",
    alt: "Portrait of Anis Soomar, waiting for a professional photograph",
    category: "man",
    desktopObjectPosition: "center",
    mobileObjectPosition: "center",
    replacementRequired: true,
    notes: "Shoot slot. Unused until a dedicated Anis portrait exists.",
  },
  cutting: {
    id: "cutting",
    desktopSrc: "/images/IMG_3731.jpg",
    mobileSrc: "/images/IMG_3731.jpg",
    alt: "Cloth being cut, waiting for a professional photograph",
    category: "hands",
    desktopObjectPosition: "center",
    mobileObjectPosition: "center",
    replacementRequired: true,
    notes: "Shoot slot. Unused until a cutting photograph exists.",
  },
  shirtWorn: {
    id: "shirtWorn",
    desktopSrc: "/images/IMG_3730.jpg",
    mobileSrc: "/images/IMG_3730.jpg",
    alt: "A bespoke shirt, waiting for a professional photograph",
    category: "garment",
    desktopObjectPosition: "center",
    mobileObjectPosition: "center",
    replacementRequired: true,
    notes: "Shoot slot. Unused until a worn-shirt photograph exists.",
  },
  bandhgala: {
    id: "bandhgala",
    desktopSrc: "/images/IMG_3730.jpg",
    mobileSrc: "/images/IMG_3730.jpg",
    alt: "A bandhgala, waiting for a professional photograph",
    category: "garment",
    desktopObjectPosition: "center",
    mobileObjectPosition: "center",
    replacementRequired: true,
    notes: "Shoot slot. Unused until a bandhgala photograph exists.",
  },
  sherwani: {
    id: "sherwani",
    desktopSrc: "/images/IMG_3730.jpg",
    mobileSrc: "/images/IMG_3730.jpg",
    alt: "A sherwani, waiting for a professional photograph",
    category: "garment",
    desktopObjectPosition: "center",
    mobileObjectPosition: "center",
    replacementRequired: true,
    notes: "Shoot slot. Unused until a sherwani photograph exists.",
  },
  houseArchive: {
    id: "houseArchive",
    desktopSrc: "/images/house-hero.jpg",
    mobileSrc: "/images/house-hero.jpg",
    alt: "House archive material, waiting to be collected",
    category: "archive",
    desktopObjectPosition: "center",
    mobileObjectPosition: "center",
    replacementRequired: true,
    notes: "Shoot/collect slot. Unused. Do not generate fake archive imagery.",
  },
} as const satisfies Record<string, ImageEntry>;

export type ImageId = keyof typeof images;

export function img(id: ImageId): ImageEntry {
  return images[id];
}
